# Generated by Django 5.2.5 on 2026-02-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_section', '0005_alter_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article_section.section', verbose_name='Раздел'),
        ),
    ]
