# Generated by Django 5.2.5 on 2026-02-17 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_section', '0007_alter_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article_section.section', verbose_name='Раздел'),
        ),
    ]
