# Generated by Django 5.2.5 on 2026-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_section', '0008_alter_article_section'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'permissions': [('view_engineering_section', 'Может видеть инженерные разделы'), ('view_sales_section', 'Может видеть разделы продаж')], 'verbose_name': 'Разделы', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='section',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.group', verbose_name='Группы с доступом'),
        ),
    ]
