# Generated by Django 5.2.5 on 2026-02-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_section', '0009_alter_article_options_alter_section_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Группы с доступом'),
        ),
    ]
